# Generated by Django 5.2.6 on 2025-09-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.CharField(help_text='Name of the Dashboard', max_length=50, unique=True)),
                ('data_source', models.URLField(blank=True, help_text='Optional: URL of source raw data', max_length=150)),
                ('data', models.JSONField(help_text='Data related to the dashboard in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboards Data',
                'verbose_name_plural': 'Dashboards Data',
            },
        ),
    ]
