# Generated by Django 6.0.1 on 2026-02-04 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlpProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Project title (e.g. 'Multi-disease serology')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the title (auto-generated from title)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("plp1", "PLP1"),
                            ("tdp", "TDP"),
                            ("plp2", "PLP2"),
                            ("test", "PLP-Test"),
                            ("pmt", "PM TDP"),
                        ],
                        help_text="Project category (e.g. PLP1, PLP2, TDP)",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full markdown content for the project detail page"
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        help_text="Featured image for the project",
                        upload_to="plp/projects/",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation timestamp (defaults to now)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Toggle visibility without deleting the record",
                    ),
                ),
            ],
            options={
                "verbose_name": "PLP Project",
                "verbose_name_plural": "PLP Projects",
                "ordering": ["-created_at"],
            },
        ),
    ]
