# Generated by Django 6.0.2 on 2026-02-10 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlpProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Project title (e.g. 'Multi-disease serology')", max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title (auto-generated from title)', max_length=255, unique=True)),
                ('category', models.CharField(choices=[('tdp', 'TDP'), ('pmt', 'PM TDP'), ('test', 'PLP-Test'), ('plp2', 'PLP2'), ('plp1', 'PLP1')], help_text='Project category (e.g. PLP1, PLP2, TDP)', max_length=20)),
                ('image', models.ImageField(help_text='Featured image for the project', upload_to='plp/projects/')),
                ('content', models.TextField(help_text='Full markdown content for the project detail page')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility without deleting the record')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp (defaults to now)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PLP Project',
                'verbose_name_plural': 'PLP Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
