"""Views for dashboards index page."""

from django.urls import reverse_lazy

from utils.views import BaseTemplateView


class DashboardsIndex(BaseTemplateView):
    """Index page for Dashboard.

    WIP: currently a simple templateview but will be updated later
    """

    template_name = "dashboards/index.html"
    title = "Data dashboards"

    # This is a temporary workaround for the MVP, the following dict
    # might be removed and the info will be fetched from DB.
    extra_context = {
        # a list of ACTIVE dashboards
        "active_dashboards": [
            {
                "name": "SARS-CoV-2 Variant Competition",
                "image": "dashboards/thumbnails/lineage_competition.jpg",
                "url": reverse_lazy("dashboards:lineage_competition"),
                "description": (
                    "Estimates of SARS-CoV-2 variant frequencies and growth rate "
                    "advantages from global SARS-CoV-2 genotype sequencing data."
                ),
            },
            {
                "name": "SARS-CoV-2 whole genome sequencing (Region Uppsala)",
                "image": "dashboards/thumbnails/variants_region_uppsala.jpg",
                "url": reverse_lazy("dashboards:variants_region_uppsala"),
                "description": (
                    "Surveillance of viral genome sequences is crucial in tracking "
                    "the spread of viral variants. This dashboard shows whole-genome "
                    "sequencing data generated by Uppsala University Hospital."
                ),
            },
            {
                "name": "Serology tests for SARS-CoV-2 at SciLifeLab",
                "image": "dashboards/thumbnails/serology_statistics.jpg",
                "url": reverse_lazy("dashboards:serology_statistics"),
                "description": (
                    "The dashboard displays the SARS-CoV-2 serology tests completed "
                    "over time at the SciLifeLab Autoimmunology and Serology "
                    "Profiling unit. The number of tests in total and the amount of "
                    "positive/negative tests over time are shown."
                ),
            },
        ],
        # a list of HISTORIC dashboards
        "historic_dashboards": [
            {
                "name": "COVID Symptom Study Sweden (Partner)",
                "image": "dashboards/thumbnails/symptom_study_sweden.jpg",
                "url": reverse_lazy("dashboards:symptom_study_sweden"),
                "description": (
                    "The COVID Symptom Study Sweden (CSSS) collects data on COVID-19 "
                    "prevalence, symptoms, and vaccinations through a smart phone app "
                    "with over 200.000 users in Sweden. Raw data can be requested for "
                    "use in research projects."
                ),
            },
            {
                "name": "CRUSH Covid Uppsala (Partner)",
                "image": "dashboards/thumbnails/crush_covid.jpg",
                "url": reverse_lazy("dashboards:crush_covid"),
                "description": (
                    "CRUSH Covid maps outbreaks in Uppsala County by visualising the "
                    "number of cases, test positivity, and geographic distribution, "
                    "among other things. Data for each postal code is available for "
                    "download and reuse."
                ),
            },
            {
                "name": "Post COVID-19 condition",
                "image": "dashboards/thumbnails/post_covid.jpg",
                "url": reverse_lazy("dashboards:post_covid"),
                "description": (
                    "The Swedish Board of Health and Welfare (Socialstyrelsen) shares "
                    "data on Post COVID-19 condition. Here, we show visualisations of "
                    "data on symptoms, healthcare contacts, and geographic "
                    "distribution, among other things."
                ),
            },
            {
                "name": "SARS-CoV-2 tests at National Pandemic Centre",
                "image": "dashboards/thumbnails/npc_statistics.jpg",
                "url": reverse_lazy("dashboards:npc_statistics"),
                "description": (
                    "The national Pandemic Centre (NPC) conducted testing related to "
                    "SARS-CoV-2 from the start of the pandemic. They show positive, "
                    "negative, and inconclusive tests. This dashboard is historic, so "
                    "no longer updated."
                ),
            },
            {
                "name": "Vaccine administration: COVID-19",
                "image": "dashboards/thumbnails/vaccines.jpg",
                "url": reverse_lazy("dashboards:vaccines"),
                "description": (
                    "The Swedish Health Agency (Folkhälsomyndigheten) provide data "
                    "and information related to COVID-19 in Sweden. Visualisations "
                    "are shown on multiple aspects of vaccination coverage, like "
                    "coverage in different counties."
                ),
            },
            {
                "name": "Amount of SARS-CoV-2 in wastewater (SEEC-KTH)",
                "image": "dashboards/thumbnails/covid_quantification_kth.png",
                "url": reverse_lazy("dashboards:covid_quantification_kth"),
                "description": (
                    "SEEC-KTH wastewater monitoring project led by associate professor "
                    "Zeynep Cetecioglu Gurol at KTH Royal Institute of Technology. "
                    "Visualizations of SARS-CoV-2 levels in wastewater from Stockholm "
                    "and Malmö, including both historic and recent data. Data collection "
                    "ceased in June 2023."
                ),
            },
            {
                "name": "Historic SARS-CoV-2 wastewater (SEEC-SLU)",
                "image": "dashboards/thumbnails/covid_quantification_kth.png",
                "url": reverse_lazy("dashboards:historic_sarscov2_wastewater"),
                "description": (
                    "Historic SARS-CoV-2 wastewater data from SEEC-SLU, including "
                    "nationwide sites plus Umeå and Örebro visualisations."
                ),
            },
        ],
    }
