"""Views for dashboards index page."""

from django.urls import reverse_lazy

from utils.views import BaseTemplateView


class DashboardsIndex(BaseTemplateView):
    """Index page for Dashboard.

    WIP: currently a simple templateview but will be updated later
    """

    template_name = "dashboards/index.html"
    title = "Data dashboards"

    # This is a temporary workaround for the MVP, the following dict
    # might be removed and the info will be fetched from DB.
    extra_context = {
        # a list of ACTIVE dashboards
        "active_dashboards": [
            {
                "name": "Register-based vaccination (RECOVAC)",
                "image": "dashboards/thumbnails/recovac.png",
                "url": reverse_lazy("dashboards:recovac"),
                "description": (
                    "Dedicated to the work of the register-based large-scale national "
                    "population study to monitor COVID-19 vaccination effectiveness and "
                    "safety (RECOVAC) project."
                ),
            },
            {
                "name": "SARS-CoV-2 Variant Competition",
                "image": "dashboards/thumbnails/lineage_competition.jpg",
                "url": reverse_lazy("dashboards:lineage_competition"),
                "description": (
                    "Estimates of SARS-CoV-2 variant frequencies and growth rate "
                    "advantages from global SARS-CoV-2 genotype sequencing data."
                ),
            },
            {
                "name": "SARS-CoV-2 whole genome sequencing (Region Uppsala)",
                "image": "dashboards/thumbnails/variants_region_uppsala.jpg",
                "url": reverse_lazy("dashboards:variants_region_uppsala"),
                "description": (
                    "Surveillance of viral genome sequences is crucial in tracking "
                    "the spread of viral variants. This dashboard shows whole-genome "
                    "sequencing data generated by Uppsala University Hospital."
                ),
            },
            {
                "name": "Serology tests for SARS-CoV-2 at SciLifeLab",
                "image": "dashboards/thumbnails/serology_statistics.jpg",
                "url": reverse_lazy("dashboards:serology_statistics"),
                "description": (
                    "The dashboard displays the SARS-CoV-2 serology tests completed "
                    "over time at the SciLifeLab Autoimmunology and Serology "
                    "Profiling unit. The number of tests in total and the amount of "
                    "positive/negative tests over time are shown."
                ),
            },
            {
                "name": "Multi-disease serology",
                "image": "dashboards/thumbnails/multidisease_serology.jpg",
                "url": reverse_lazy("dashboards:multidisease_serology"),
                "description": (
                    "A summary of the progress in developing a multi-disease serology "
                    "assay, a key component of pandemic preparedness. Information "
                    "about externally produced antigens is also provided. "
                ),
            },{
                "name": "SvarmIT: interactive resistance monitoring",
                "image": "dashboards/thumbnails/external/sva_logo.png",
                "url": "https://www.sva.se/djurhaelsa/antibiotika/oevervakning/svarmit-interaktivt-resistensoevervakningsverktyg/",
                "description": (
                    "Interactive visualisation to show the occurrence of resistance "
                    "among different types of bacteria from animals."
                ),
            },
            {
                "name": "Avian Influenza: infection status with map",
                "image": "dashboards/thumbnails/external/sva_logo.png",
                "url": "https://www.sva.se/djurhaelsa/djursjukdomar-a-oe/sjukdomar/faagelinfluensa/faagelinfluensa-smittlaege-med-karta/",
                "description": (
                    "The transmission of avian influenza is variable "
                    "and is continuously monitored by sampling domestic birds that "
                    "are reported to have symptoms that may indicate avian influenza."
                ),
            },
            {
                "name": "Campylobacter in broiler chickens",
                "image": "dashboards/thumbnails/external/sva_logo.png",
                "url": "https://svastatichosting.z6.web.core.windows.net/maps/campy_graph/barchart.html",
                "description": (
                    "Surveillance dedicated to monitor campylobacter in chickens."
                ),
            },
            {
                "name": "Covid-19 – Confirmed cases in Sweden",
                "image": "dashboards/thumbnails/external/fohm_logo.png",
                "url": "https://www.folkhalsomyndigheten.se/fall-covid-19/",
                "description": (
                    "Shows an up-to-date interactive visualisation "
                    "of the number of confirmed COVID-19 cases in Sweden over time "
                    "(with options to compare by region and other filters)."
                ),
            },
            {
                "name": "Covid-19 – Tested with PCR ",
                "image": "dashboards/thumbnails/external/fohm_logo.png",
                "url": "https://www.folkhalsomyndigheten.se/PCR-covid-19/",
                "description": (
                    "Visualisation of weekly PCR testing statistics for COVID-19 in Sweden, "
                    "including the number of individuals tested, PCR tests conducted, "
                    "and related breakdowns by age, region and other variables."
                ),
            },
            {
                "name": "Covid-19 – Vaccinations ",
                "image": "dashboards/thumbnails/external/fohm_logo.png",
                "url": "https://www.folkhalsomyndigheten.se/vaccination-covid-19/",
                "description": (
                    "COVID-19 vaccination coverage in Sweden, showing numbers and "
                    "proportions of vaccinated individuals over time, broken down by age group,  "
                    "region, and dose type, using data from the national vaccinations database."
                ),
            },
            {
                "name": "Influenza – Confirmed cases in Sweden",
                "image": "dashboards/thumbnails/external/fohm_logo.png",
                "url": "https://www.folkhalsomyndigheten.se/faktablad/fall-influensa/",
                "description": (
                    "Laboratory confirmed influenza cases in Sweden over time, with options "
                    "to explore trends by region, age group and calendar week based on data  "
                    "from the national health data system."
                ),
            },
            {
                "name": "RS virus infection – Confirmed cases in Sweden",
                "image": "dashboards/thumbnails/external/fohm_logo.png",
                "url": "https://www.folkhalsomyndigheten.se/faktablad/fall-RS-virus/",
                "description": (
                    "Shows the statistics of the number of confirmed RS‑virus "
                    "(respiratory syncytial virus) cases in Sweden over time, allowing "
                    "exploration by region, age group and other filters using "
                    "national surveillance data."
                ),
            },
            {
                "name": "Real-time tracking of influenza A/H5N1 virus evolution",
                "image": "dashboards/thumbnails/external/nextstrain_logo.png",
                "url": "https://nextstrain.org/avian-flu/h5n1/ha/2y?c=country&f_country=Sweden",
                "description": (
                    "Phylogenetic visualisation of avian influenza A (H5N1) hemagglutinin (HA) "
                    "gene sequences from the past two years, highlighting the genetic "
                    "relationships and temporal evolution of strains with a filter "
                    "showing sequences from Sweden in the global context."
                ),
            },
            {
                "name": "Real-time tracking of influenza A/H3N2 evolution",
                "image": "dashboards/thumbnails/external/nextstrain_logo.png",
                "url": "https://nextstrain.org/seasonal-flu/h3n2/ha/2y?c=country&f_country=Sweden",
                "description": (
                    "Phylogenetic visualisation of the hemagglutinin (HA) "
                    "gene of seasonal influenza A (H3N2) viruses over the past "
                    "2 years, with sequences from Sweden highlighted. "
                ),
            },
            {
                "name": "Genomic epidemiology of SARS-CoV-2",
                "image": "dashboards/thumbnails/external/nextstrain_logo.png",
                "url": "https://nextstrain.org/ncov/open/global/6m?c=country&f_country=Sweden",
                "description": (
                    "Phylogenetic and temporal visualisation of global SARS-CoV-2 "
                    "genomic data over the past six months, with sequences from Sweden "
                    "highlighted to help explore how Swedish data relate to worldwide "
                    "SARS-CoV-2 diversity and spread. "
                ),
            },
             {
                "name": "SARS-CoV-2 phylogeny",
                "image": "dashboards/thumbnails/external/nextstrain_logo.png",
                "url": "https://nextstrain.org/groups/neherlab/ncov/sweden?c=clade_membership&f_country=Sweden&p=grid&r=division",
                "description": (
                    "Genomic surveillance visualisation showing the phylogenetic relationships and "
                    "clade membership of SARS-CoV-2 sequences from Sweden, allowing exploration of "
                    "how different viral lineages are distributed across Swedish regions and over "
                    "time in the context of the global pandemic."
                ),
            },
            {
                "name": "Real-time tracking of measles N450 virus evolution",
                "image": "dashboards/thumbnails/external/nextstrain_logo.png",
                "url": "https://nextstrain.org/measles/N450?c=country&f_country=Sweden",
                "description": (
                    "Phylogenetic visualisation of measles N450 virus sequences, "
                    "showing measles viruses from Sweden enabling exploration of transmission "
                    "patterns and lineage diversity. "
                ),
            },
            {
                "name": "Real-time tracking of Mycobacterium tuberculosis full genome evolution",
                "image": "dashboards/thumbnails/external/nextstrain_logo.png",
                "url": "https://nextstrain.org/tb/global?f_country=Sweden",
                "description": (
                    "Mycobacterium tuberculosis genomic data, with Swedish isolates highlighted "
                    "to help explore their evolutionary relationships, lineages and distribution "
                    "in the context of worldwide TB diversity. "
                ),
            },
        ],
        # a list of HISTORIC dashboards
        "historic_dashboards": [
            {
                "name": "COVID Symptom Study Sweden (Partner)",
                "image": "dashboards/thumbnails/symptom_study_sweden.jpg",
                "url": reverse_lazy("dashboards:symptom_study_sweden"),
                "description": (
                    "The COVID Symptom Study Sweden (CSSS) collects data on COVID-19 "
                    "prevalence, symptoms, and vaccinations through a smart phone app "
                    "with over 200.000 users in Sweden. Raw data can be requested for "
                    "use in research projects."
                ),
            },
            {
                "name": "CRUSH Covid Uppsala (Partner)",
                "image": "dashboards/thumbnails/crush_covid.jpg",
                "url": reverse_lazy("dashboards:crush_covid"),
                "description": (
                    "CRUSH Covid maps outbreaks in Uppsala County by visualising the "
                    "number of cases, test positivity, and geographic distribution, "
                    "among other things. Data for each postal code is available for "
                    "download and reuse."
                ),
            },
            {
                "name": "Historic influenza virus in wastewater (SLU)",
                "image": "dashboards/thumbnails/historic_influenza.jpg",
                "url": reverse_lazy("dashboards:historic_influenza"),
                "description": (
                    "Historic data of Influenza A and B virus levels in wastewater "
                    "across Sweden from SLU-SEEC."
                ),
            },
            {
                "name": "Post COVID-19 condition",
                "image": "dashboards/thumbnails/post_covid.jpg",
                "url": reverse_lazy("dashboards:post_covid"),
                "description": (
                    "The Swedish Board of Health and Welfare (Socialstyrelsen) shares "
                    "data on Post COVID-19 condition. Here, we show visualisations of "
                    "data on symptoms, healthcare contacts, and geographic "
                    "distribution, among other things."
                ),
            },
            {
                "name": "SARS-CoV-2 tests at National Pandemic Centre",
                "image": "dashboards/thumbnails/npc_statistics.jpg",
                "url": reverse_lazy("dashboards:npc_statistics"),
                "description": (
                    "The national Pandemic Centre (NPC) conducted testing related to "
                    "SARS-CoV-2 from the start of the pandemic. They show positive, "
                    "negative, and inconclusive tests. This dashboard is historic, so "
                    "no longer updated."
                ),
            },
            {
                "name": "Swedish COVID-19 publications over 5 years",
                "image": "dashboards/thumbnails/historic_covid_publications.jpg",
                "url": reverse_lazy("dashboards:historic_covid_publications"),
                "description": (
                    "A summary of the COVID-19 and SARS-CoV-2 publications produced involving at "
                    "least one contributor from a Swedish university or research institute. Shows "
                    "publications over time and key words/phrases within them."
                ),
            },
            {
                "name": "Vaccine administration: COVID-19",
                "image": "dashboards/thumbnails/vaccines.jpg",
                "url": reverse_lazy("dashboards:vaccines"),
                "description": (
                    "The Swedish Health Agency (Folkhälsomyndigheten) provide data "
                    "and information related to COVID-19 in Sweden. Visualisations "
                    "are shown on multiple aspects of vaccination coverage, like "
                    "coverage in different counties."
                ),
            },
            {
                "name": "Amount of SARS-CoV-2 in wastewater (SEEC-KTH)",
                "image": "dashboards/thumbnails/covid_quantification_kth.png",
                "url": reverse_lazy("dashboards:covid_quantification_kth"),
                "description": (
                    "SEEC-KTH wastewater monitoring project led by associate professor "
                    "Zeynep Cetecioglu Gurol at KTH Royal Institute of Technology. "
                    "Visualizations of SARS-CoV-2 levels in wastewater from Stockholm "
                    "and Malmö, including both historic and recent data. Data collection "
                    "ceased in June 2023."
                ),
            },
            {
                "name": "Historic SARS-CoV-2 wastewater (SEEC-SLU)",
                "image": "dashboards/thumbnails/covid_quantification_kth.png",
                "url": reverse_lazy("dashboards:historic_sarscov2_wastewater"),
                "description": (
                    "Historic SARS-CoV-2 wastewater data from SEEC-SLU, including "
                    "nationwide sites plus Umeå and Örebro visualisations."
                ),
            },
        ],
    }
