from django.urls import reverse_lazy

from utils.views import BaseTemplateView


class DashboardsIndex(BaseTemplateView):
    """Index page for Dashboard

    WIP: currently a simple templateview but will be updated later
    """

    template_name = "dashboards/index.html"
    title = "Data dashboards"

    # This is a temporary workaround for the MVP, the following dict
    # might be removed and the info will be fetched from DB.
    extra_context = {
        # a list of ACTIVE dashboards
        "active_dashboards": [
            {
                "name": "SARS-CoV-2 Variant Competition",
                "image": "dashboards/lineage_competition.jpg",
                "url": reverse_lazy("dashboards:lineage_competition"),
                "description": (
                    "Estimates of SARS-CoV-2 variant frequencies and growth rate "
                    "advantages from global SARS-CoV-2 genotype sequencing data."
                ),
            },
            {
                "name": "Serology tests for SARS-CoV-2 at SciLifeLab",
                "image": "dashboards/serology_statistics.jpg",
                "url": reverse_lazy("dashboards:serology_statistics"),
                "description": (
                    "The dashboard displays the SARS-CoV-2 serology tests completed "
                    "over time at the SciLifeLab Autoimmunology and Serology "
                    "Profiling unit. The number of tests in total and the amount of "
                    "positive/negative tests over time are shown."
                ),
            },
            {
                "name": "SARS-CoV-2 whole genome sequencing (Region Uppsala)",
                "image": "dashboards/variants_region_uppsala.jpg",
                "url": reverse_lazy("dashboards:variants_region_uppsala"),
                "description": (
                    "Surveillance of viral genome sequences is crucial in tracking "
                    "the spread of viral variants. This dashboard shows whole-genome "
                    "sequencing data generated by Uppsala University Hospital."
                ),
            },
        ],
        # a list of HISTORIC dashboards
        "historic_dashboards": [],
    }
