import json
import logging
from urllib.error import URLError
from urllib.request import urlopen

from django.core.cache import cache
from utils.views import BaseTemplateView

logger = logging.getLogger(__name__)


class VariantsRegionUppsala(BaseTemplateView):
    """SARS-CoV-2 variants detected in Region Uppsala dashboard page.

    This dashboard view class renders the template for the Uppsala University Hospital
    whole-genome sequencing surveillance dashboard, which displays SARS-CoV-2 variant
    data from the Uppsala region. It fetches Plotly JSON data from blobserver and
    passes it to the template for rendering.

    Attributes:
        template_name: Template for rendering the dashboard.
        title: Title displayed in the rendered page's banner section.
        description: Description to be used in the HTML's head.
    """

    template_name = "dashboards/variants_region_uppsala.html"
    title = "SARS-CoV-2 variants detected in Region Uppsala"
    description = (
        "Surveillance of viral genome sequences is crucial in tracking the spread of "
        "viral variants. This dashboard shows whole-genome sequencing data generated by "
        "Uppsala University Hospital."
    )

    # Plotly data source URLs mapped to chart container IDs
    PLOTLY_SOURCES = {
        "plotly-lineage-six-recent": "https://blobserver.dc.scilifelab.se/blob/lineage_six_recent.json",
        "plotly-lineage-four-recent": "https://blobserver.dc.scilifelab.se/blob/lineage_four_recent.json",
        "plotly-lineage-wholetime": "https://blobserver.dc.scilifelab.se/blob/lineage_one_wholetime.json",
    }

    def _fetch_plotly_data(self, url: str, cache_key: str, timeout: int = 10) -> dict | None:
        """Fetch Plotly JSON data from URL with caching.

        Args:
            url: URL to fetch JSON data from.
            cache_key: Cache key for storing/retrieving data.
            timeout: Request timeout in seconds.

        Returns:
            Parsed JSON data as dict, or None if fetch fails.
        """
        # Try to get from cache first (5 minute cache)
        cached_data = cache.get(cache_key)
        if cached_data is not None:
            return cached_data

        try:
            with urlopen(url, timeout=timeout) as response:
                data = json.loads(response.read().decode("utf-8"))
                # Cache for 5 minutes
                cache.set(cache_key, data, 300)
                return data
        except (URLError, json.JSONDecodeError, TimeoutError) as e:
            logger.warning(f"Failed to fetch Plotly data from {url}: {e}")
            return None

    def get_context_data(self, **kwargs):
        """Add Plotly JSON data to template context."""
        context = super().get_context_data(**kwargs)

        # Fetch Plotly data for each visualization
        # Keys are chart container IDs (with hyphens for HTML) for the init script
        # Also provide individual variables for easy template access
        plotly_data = {}
        for chart_id, url in self.PLOTLY_SOURCES.items():
            cache_key = f"plotly_data_{chart_id}"
            data = self._fetch_plotly_data(url, cache_key)
            plotly_data[chart_id] = data

        context["plotly_data"] = plotly_data
        # Also provide individual chart data for easier template access
        context["plotly_lineage_six_recent"] = plotly_data.get("plotly-lineage-six-recent")
        context["plotly_lineage_four_recent"] = plotly_data.get("plotly-lineage-four-recent")
        context["plotly_lineage_wholetime"] = plotly_data.get("plotly-lineage-wholetime")
        return context
