from .plotly import PlotlyDashboardView


class VariantsRegionUppsala(PlotlyDashboardView):
    """SARS-CoV-2 variants detected in Region Uppsala dashboard page.

    This dashboard view class renders the template for the Uppsala University Hospital
    whole-genome sequencing surveillance dashboard, which displays SARS-CoV-2 variant
    data from the Uppsala region. It fetches Plotly JSON data from blobserver and
    passes it to the template for rendering.

    The view fetches Plotly visualization data from external blobserver URLs with
    5-minute caching to reduce external API calls. Data is passed to the template
    as a dictionary with underscore-based chart IDs for direct template access.

    Attributes:
        template_name: Template for rendering the dashboard.
        title: Title displayed in the rendered page's banner section.
        description: Description to be used in the HTML's head.
        PLOTLY_SOURCES: Dictionary mapping chart IDs to blobserver URLs.

    Example:
        The view automatically fetches and caches Plotly data:

        .. code-block:: python

            class VariantsRegionUppsala(PlotlyDashboardView):
                template_name = "dashboards/variants_region_uppsala.html"
                PLOTLY_SOURCES = {
                    "plotly_lineage_six_recent": "https://blobserver.dc.scilifelab.se/blob/lineage_six_recent.json",
                }

        Template context includes:
        - `plotly_data`: Dictionary of all chart data keyed by chart ID
        
        Template access example:
            plotly_data.plotly_lineage_six_recent
    """

    template_name = "dashboards/variants_region_uppsala.html"
    title = "SARS-CoV-2 variants detected in Region Uppsala"
    description = (
        "Surveillance of viral genome sequences is crucial in tracking the spread of "
        "viral variants. This dashboard shows whole-genome sequencing data generated by "
        "Uppsala University Hospital."
    )

    # Plotly data source URLs mapped to chart container IDs
    # Using underscores for IDs to enable direct template access
    PLOTLY_SOURCES = {
        "plotly_lineage_six_recent": "https://blobserver.dc.scilifelab.se/blob/lineage_six_recent.json",
        "plotly_lineage_four_recent": "https://blobserver.dc.scilifelab.se/blob/lineage_four_recent.json",
        "plotly_lineage_wholetime": "https://blobserver.dc.scilifelab.se/blob/lineage_one_wholetime.json",
    }
