# Generated by Django 5.2.6 on 2025-10-31 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('data_highlight', 'Data Highlight'), ('editorial', 'Editorial')], default='data_highlight', help_text='Type of content: Data Highlight or Editorial', max_length=50)),
                ('title', models.CharField(help_text='Title of the article', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title (auto-generated from title)', max_length=255, unique=True)),
                ('summary', models.TextField(help_text='Brief summary of the article for display in cards')),
                ('content', models.TextField(help_text='Full content in markdown format displayed on detail page')),
                ('announcement', models.TextField(blank=True, help_text='Optional announcement message displayed at the top of the article')),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags for related content matching and search')),
                ('author', models.CharField(blank=True, help_text='Author name or names for the article (optional)', max_length=255)),
                ('featured_image', models.ImageField(help_text='Featured image for the article', upload_to='articles/images/')),
                ('figure_caption', models.TextField(blank=True, help_text='Caption for the featured image (optional)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this article is active and visible')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date (defaults to current date if not provided)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topics', models.ManyToManyField(blank=True, help_text='Research topics associated with this article (optional)', to='topics.topic')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
