# Generated by Django 5.2.6 on 2025-12-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationPathogens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the pathogen', max_length=255)),
                ('query_string', models.CharField(help_text='Query string used to fetch publications related to the pathogen', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pathogen is active and used for fetching publications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publications Pathogen',
                'verbose_name_plural': 'Publications Pathogens',
            },
        ),
    ]
