from django.views.generic import TemplateView
from django.urls import reverse_lazy
from pages.topics.models import Topic
from pages.articles.models import Article
from pages.news.models import News
import logging

logger = logging.getLogger(__name__)


class Home(TemplateView):
    template_name = "home/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Fetch active dashboards with thumbnails
        context['dashboards'] = [
            {
                "name": "SARS-CoV-2 Variant Competition",
                "image": "dashboards/thumbnails/lineage_competition.jpg",
                "url": reverse_lazy("dashboards:lineage_competition"),
                "description": (
                    "Estimates of SARS-CoV-2 variant frequencies and growth rate "
                    "advantages from global SARS-CoV-2 genotype sequencing data."
                ),
            },
            {
                "name": "SARS-CoV-2 whole genome sequencing (Region Uppsala)",
                "image": "dashboards/thumbnails/variants_region_uppsala.jpg",
                "url": reverse_lazy("dashboards:variants_region_uppsala"),
                "description": (
                    "Surveillance of viral genome sequences is crucial in tracking "
                    "the spread of viral variants. This dashboard shows whole-genome "
                    "sequencing data generated by Uppsala University Hospital."
                ),
            },
            {
                "name": "Serology tests for SARS-CoV-2 at SciLifeLab",
                "image": "dashboards/thumbnails/serology_statistics.jpg",
                "url": reverse_lazy("dashboards:serology_statistics"),
                "description": (
                    "The dashboard displays the SARS-CoV-2 serology tests completed "
                    "over time at the SciLifeLab Autoimmunology and Serology "
                    "Profiling unit."
                ),
            },
        ]
        
        context['topics'] = Topic.objects.filter(is_active=True)[:3]
        context['articles'] = Article.objects.filter(is_active=True).order_by('-created_at')[:3]
        context['news'] = News.objects.filter(is_active=True).order_by('-created_at')[:5]
        
        # Print context for debugging
        print("=" * 80)
        print("HOME VIEW CONTEXT:")
        print(f"Dashboards count: {len(context['dashboards'])}")
        print(f"Topics count: {context['topics'].count()}")
        print(f"Articles count: {context['articles'].count()}")
        print(f"News count: {context['news'].count()}")
        print(f"Full context keys: {list(context.keys())}")
        print("=" * 80)
        for n in context['news']:
            print(n.title)
            print(n.created_at)
            
        for t in context['topics']:
            print(t)
        for a in context['articles']:
            print(a)
        
        return context
    title = "Swedish Pathogens Portal: supporting pandemic preparedness"
