"""Home page view and context logic."""

import logging

from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.views import View

from pages.highlights_and_editorials.models import HighlightsAndEditorials
from pages.news.models import News
from pages.topics.models import Topic

logger = logging.getLogger(__name__)


class Home(View):
    """Home page view displaying dashboards, articles, topics, and news.

    This view fetches and displays:
    - Active dashboards (hardcoded list of 3)
    - Latest articles (3 most recent active articles)
    - Active topics (3 most recent active topics)
    - Latest news (5 most recent active news items)

    Attributes:
        template_name (str): Path to the home page template
        title (str): Page title for SEO and context
        description (str): Page description for SEO and context
    """

    template_name = "home/index.html"
    title = "Swedish Pathogens Portal: supporting pandemic preparedness"
    description = (
        "The Swedish Pathogens Portal provides information about available datasets, resources, "
        "tools, and services related to pandemic preparedness in Sweden. We offer support to all "
        "those involved in pandemic preparedness research that are affiliated with a Swedish "
        "research institution or university."
    )

    def get(self, request: HttpRequest) -> HttpResponse:
        """Handle GET requests for the home page."""

        context = {"title": self.title, "description": self.description}

        # Fetch active dashboards with thumbnails
        context["dashboards"] = [
            {
                "name": "SLU-SEEC Wastewater Surveillance",
                "image": static("dashboards/thumbnails/slu_wastewater.jpg"),
                "url": reverse_lazy("dashboards:slu_overview"),
                "description": (
                    "Explore pathogens levels in wastewater across Sweden. Weekly data from "
                    "SLU-SEEC tracks pathogens trends, covering a significant portion of the "
                    "population, and assists in predicting potential outbreaks."
                ),
            },
            {
                "name": "SARS-CoV-2 whole genome sequencing (Region Uppsala)",
                "image": static("dashboards/thumbnails/variants_region_uppsala.jpg"),
                "url": reverse_lazy("dashboards:variants_region_uppsala"),
                "description": (
                    "Surveillance of viral genome sequences is crucial in tracking "
                    "the spread of viral variants. This dashboard shows whole-genome "
                    "sequencing data generated by Uppsala University Hospital."
                ),
            },
            {
                "name": "Serology tests for SARS-CoV-2 at SciLifeLab",
                "image": static("dashboards/thumbnails/serology_statistics.jpg"),
                "url": reverse_lazy("dashboards:serology_statistics"),
                "description": (
                    "The dashboard displays the SARS-CoV-2 serology tests completed "
                    "over time at the SciLifeLab Autoimmunology and Serology "
                    "Profiling unit."
                ),
            },
        ]

        context["topics"] = Topic.objects.filter(is_active=True)[:3]
        context["articles"] = HighlightsAndEditorials.objects.filter(is_active=True).order_by(
            "-created_at"
        )[:3]
        context["news"] = News.objects.filter(is_active=True).order_by("-created_at")[:5]

        return render(request, self.template_name, context)
