# Generated by Django 6.0.2 on 2026-02-10 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outbreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the outbreak (e.g., 'Hepatitis A (September 2025)')", max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name (auto-generated from name)', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('current', 'Current'), ('historical', 'Historical')], default='current', help_text='Whether this is a current or historical outbreak', max_length=20)),
                ('description', models.TextField(help_text='Brief description of the outbreak to display in cards')),
                ('image', models.ImageField(help_text='Thumbnail image for the outbreak card display', upload_to='outbreaks/images/')),
                ('content', models.TextField(help_text='Rich text content in markdown format (displayed on detail page)')),
                ('location', models.CharField(blank=True, help_text="Geographic location (e.g., 'Sweden', 'International')", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this outbreak is active and visible')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date (defaults to current date if not provided)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outbreak',
                'verbose_name_plural': 'Outbreaks',
                'ordering': ['-created_at'],
            },
        ),
    ]
