# Generated by Django 5.2.6 on 2025-12-02 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Outbreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the outbreak (e.g., 'Hepatitis A (September 2025)')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name (auto-generated from name)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("current", "Current"), ("historical", "Historical")],
                        default="current",
                        help_text="Whether this is a current or historical outbreak",
                        max_length=20,
                    ),
                ),
                (
                    "thumbnail_image",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image for the outbreak card display (optional)",
                        null=True,
                        upload_to="outbreaks/images/",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description of the outbreak to display in cards"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Rich text content in markdown format (displayed on detail page)"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Geographic location (e.g., 'Sweden', 'International')",
                        max_length=255,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="When the outbreak started (optional)",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="When the outbreak ended (null for current outbreaks)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this outbreak is active and visible",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date (defaults to current date if not provided)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Outbreak",
                "verbose_name_plural": "Outbreaks",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
    ]
