# Generated by Django 5.2.6 on 2025-10-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the data highlight', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title (auto-generated from title)', max_length=255, unique=True)),
                ('summary', models.TextField(help_text='Brief summary of the highlight for display in cards')),
                ('content', models.TextField(help_text='Full content in markdown format displayed on detail page')),
                ('announcement', models.TextField(blank=True, help_text='Optional announcement message displayed at the top of the highlight')),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags for related content matching and search')),
                ('featured_image', models.ImageField(help_text='Featured image for the highlight', upload_to='highlights/images/')),
                ('figure_caption', models.TextField(blank=True, help_text='Caption for the featured image (optional)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this highlight is active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topics', models.ManyToManyField(blank=True, help_text='Research topics associated with this highlight (optional)', to='topics.topic')),
            ],
            options={
                'verbose_name': 'Data Highlight',
                'verbose_name_plural': 'Data Highlights',
                'ordering': ['-created_at'],
            },
        ),
    ]
