# Generated by Django 6.0.2 on 2026-02-10 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of news item', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title (auto-generated from Title)', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Short description for news index page')),
                ('image', models.ImageField(help_text='Image to be used in index and detail page', upload_to='news/images/')),
                ('content', models.TextField(help_text='Rich text content in markdown format (displayed on news detail page)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this news is active and visible')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date (defaults to current date if not provided)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-created_at'],
            },
        ),
    ]
