# trivy-scheduled.yaml
# Trivy: Scan of current branch
# Trivy is a comprehensive and versatile security scanner.
# Trivy has scanners that look for security issues,
# and targets where it can find those issues.
# https://github.com/aquasecurity/trivy
#
# This runs on scheduled to run on every Monday and Thursday at 12:12
# --------------------------------------------------------------------
---
name: Trivy - scheduled scan

on:
  workflow_dispatch:
  schedule:
    - cron: '12 12 * * MON,THU'

concurrency:
  group: trivy-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    permissions:
      contents: read
      security-events: write
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Trivy vulnerability scanner
        env:
          TRIVY_DB_REPOSITORY: >-
            ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: ghcr.io/scilifelabdatacentre/swedish-pathogens-portal:main
          scanners: "vuln,secret"  # Default but being explicit
          # ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: "0"  # Don't fail job if vuln found (on scheduled)

      - name: Upload Trivy scan results to GitHub Security tab
        if: always()  # Publish results to security tab even if scan fails
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
          category: trivy-cron
