# Generated by Django 6.0.2 on 2026-02-09 15:01

import django.contrib.postgres.fields
import django.contrib.postgres.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catalogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the resource", max_length=150, unique=True
                    ),
                ),
                ("link", models.URLField(help_text="External link to the resource")),
                (
                    "thumbnail_image",
                    models.ImageField(
                        help_text="Thumbnail image for the resource card",
                        upload_to="catalogue/images/",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description for the resource card"),
                ),
                (
                    "data_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("Biochemistry", "Biochemistry"),
                                ("Drug discovery", "Drug discovery"),
                                (
                                    "Genomics & transcriptomics",
                                    "Genomics & transcriptomics",
                                ),
                                ("Health", "Health"),
                                ("Imaging", "Imaging"),
                                ("Other", "Other"),
                                ("Protein", "Protein"),
                                ("Public health", "Public health"),
                                ("Serology", "Serology"),
                                (
                                    "Social science and humanities",
                                    "Social science and humanities",
                                ),
                            ],
                            max_length=50,
                        ),
                        help_text="Data type classification (select one or more)",
                        validators=[
                            django.contrib.postgres.validators.ArrayMinLengthValidator(
                                1
                            )
                        ],
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Optional keywords for the resource, separated by commas",
                    ),
                ),
                (
                    "category",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("tools_catalogue", "Tools catalogue"),
                                ("data_repositories", "Data repositories"),
                                ("data_sources", "Data sources"),
                            ],
                            max_length=50,
                        ),
                        help_text="Which page(s) should display this resource (select one or more)",
                        validators=[
                            django.contrib.postgres.validators.ArrayMinLengthValidator(
                                1
                            )
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this resource is active and visible",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Catalogue entry",
                "verbose_name_plural": "Catalogue entries",
                "ordering": ["name"],
            },
        ),
    ]
